apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: metrics-quarkus-servicemonitor
  name: metrics-quarkus-servicemonitor
  namespace: metrics-quarkus
spec:
  endpoints:
  - interval: 5s
    targetPort: 8080
    path: /q/metrics
    scheme: http
  selector:
    matchLabels:
      app: metrics-quarkus
